openapi: 3.1.0
info:
  title: Universal Logout API
  termsOfService: https://developer.okta.com/terms/
  contact:
    name: Okta Developer Team
    url: https://developer.okta.com/
    email: devex-public@okta.com
  license:
    name: Apache-2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
  version: 2.7.0
  x-logo:
    url: logo.svg
    backgroundColor: transparent
    altText: Okta Logo
externalDocs:
  description: Find more info here
  url: https://developer.okta.com/docs/guides/oin-universal-logout-overview/
servers:
  - url: https://saas.example
paths:
  /universal-logout:
    post:
      summary: This documentation has moved!
      description: |-
        Find the new docs on [developer.okta.com](https://developer.okta.com/docs/guides/oin-universal-logout-overview/)
